name: manage-azure-policy-d7f41863
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'

permissions:
  id-token: write
## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Automation_to_Log_Analytics_workspace_Deploy-Diagnostics-AA/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_API_for_FHIR_to_Log_Analytics_workspace_Deploy-Diagnostics-ApiForFHIR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_CDN_Endpoint_to_Log_Analytics_workspace_Deploy-Diagnostics-CDNEndpoints/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Cognitive_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-CognitiveServices/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Cosmos_DB_to_Log_Analytics_workspace_Deploy-Diagnostics-CosmosDB/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Databricks_to_Log_Analytics_workspace_Deploy-Diagnostics-Databricks/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Data_Explorer_Cluster_to_Log_Analytics_workspace_Deploy-Diagnostics-DataExplorerCluster/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Factory_to_Log_Analytics_workspace_Deploy-Diagnostics-DataFactory/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_subscriptions_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_System_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSystemTopic/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridTopic/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Front_Door_to_Log_Analytics_workspace_Deploy-Diagnostics-FrontDoor/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_HDInsight_to_Log_Analytics_workspace_Deploy-Diagnostics-HDInsight/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_integration_service_environment_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsISE/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_MariaDB_to_Log_Analytics_workspace_Deploy-Diagnostics-MariaDB/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Media_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-MediaService/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Machine_Learning_workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-MlWorkspace/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Database_for_MySQL_to_Log_Analytics_workspace_Deploy-Diagnostics-MySQL/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Database_for_PostgreSQL_to_Log_Analytics_workspace_Deploy-Diagnostics-PostgreSQL/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Power_BI_Embedded_to_Log_Analytics_workspace_Deploy-Diagnostics-PowerBIEmbedded/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Redis_Cache_to_Log_Analytics_workspace_Deploy-Diagnostics-RedisCache/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Relay_to_Log_Analytics_workspace_Deploy-Diagnostics-Relay/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SignalR_to_Log_Analytics_workspace_Deploy-Diagnostics-SignalR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Elastic_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLElasticPools/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Managed_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLMI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Time_Series_Insights_to_Log_Analytics_workspace_Deploy-Diagnostics-TimeSeriesInsights/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Application_group_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDAppGroup/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Host_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDHostPools/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDWorkspace/**'
#      - .github/workflows/manage-azure-policy-d7f41863.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
     environment:prod
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
    - name: Azure Login using OIDC
      uses: ./.github/workflows/
      with:
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |   
    
          initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Automation_to_Log_Analytics_workspace_Deploy-Diagnostics-AA/**
          policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**
          policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**
          policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**
          policies/Deploy_Diagnostic_Settings_for_Azure_API_for_FHIR_to_Log_Analytics_workspace_Deploy-Diagnostics-ApiForFHIR/**
          policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**
          policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**
          policies/Deploy_Diagnostic_Settings_for_CDN_Endpoint_to_Log_Analytics_workspace_Deploy-Diagnostics-CDNEndpoints/**
          policies/Deploy_Diagnostic_Settings_for_Cognitive_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-CognitiveServices/**
          policies/Deploy_Diagnostic_Settings_for_Cosmos_DB_to_Log_Analytics_workspace_Deploy-Diagnostics-CosmosDB/**
          policies/Deploy_Diagnostic_Settings_for_Databricks_to_Log_Analytics_workspace_Deploy-Diagnostics-Databricks/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Data_Explorer_Cluster_to_Log_Analytics_workspace_Deploy-Diagnostics-DataExplorerCluster/**
          policies/Deploy_Diagnostic_Settings_for_Data_Factory_to_Log_Analytics_workspace_Deploy-Diagnostics-DataFactory/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_subscriptions_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSub/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_System_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSystemTopic/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridTopic/**
          policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**
          policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**
          policies/Deploy_Diagnostic_Settings_for_Front_Door_to_Log_Analytics_workspace_Deploy-Diagnostics-FrontDoor/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**
          policies/Deploy_Diagnostic_Settings_for_HDInsight_to_Log_Analytics_workspace_Deploy-Diagnostics-HDInsight/**
          policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**
          policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_integration_service_environment_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsISE/**
          policies/Deploy_Diagnostic_Settings_for_MariaDB_to_Log_Analytics_workspace_Deploy-Diagnostics-MariaDB/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Media_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-MediaService/**
          policies/Deploy_Diagnostic_Settings_for_Machine_Learning_workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-MlWorkspace/**
          policies/Deploy_Diagnostic_Settings_for_Database_for_MySQL_to_Log_Analytics_workspace_Deploy-Diagnostics-MySQL/**
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**
          policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**
          policies/Deploy_Diagnostic_Settings_for_Database_for_PostgreSQL_to_Log_Analytics_workspace_Deploy-Diagnostics-PostgreSQL/**
          policies/Deploy_Diagnostic_Settings_for_Power_BI_Embedded_to_Log_Analytics_workspace_Deploy-Diagnostics-PowerBIEmbedded/**
          policies/Deploy_Diagnostic_Settings_for_Redis_Cache_to_Log_Analytics_workspace_Deploy-Diagnostics-RedisCache/**
          policies/Deploy_Diagnostic_Settings_for_Relay_to_Log_Analytics_workspace_Deploy-Diagnostics-Relay/**
          policies/Deploy_Diagnostic_Settings_for_SignalR_to_Log_Analytics_workspace_Deploy-Diagnostics-SignalR/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Elastic_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLElasticPools/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Managed_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLMI/**
          policies/Deploy_Diagnostic_Settings_for_Time_Series_Insights_to_Log_Analytics_workspace_Deploy-Diagnostics-TimeSeriesInsights/**
          policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**
          policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Application_group_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDAppGroup/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Host_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDHostPools/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDWorkspace/**
